/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/uA2GhPuJY4I
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"

export function mini caiender() {
  return (
    <div className="bg-white rounded-lg shadow-lg p-4 dark:bg-gray-950">
      <div className="flex items-center justify-between mb-4">
        <div className="text-lg font-medium">May 2024</div>
        <div className="flex items-center gap-2">
          <Button size="icon" variant="ghost">
            <ChevronLeftIcon className="w-5 h-5" />
          </Button>
          <Button size="icon" variant="ghost">
            <ChevronRightIcon className="w-5 h-5" />
          </Button>
        </div>
      </div>
      <div className="grid grid-cols-7 gap-2 text-center">
        <div className="text-gray-500 dark:text-gray-400">Sun</div>
        <div className="text-gray-500 dark:text-gray-400">Mon</div>
        <div className="text-gray-500 dark:text-gray-400">Tue</div>
        <div className="text-gray-500 dark:text-gray-400">Wed</div>
        <div className="text-gray-500 dark:text-gray-400">Thu</div>
        <div className="text-gray-500 dark:text-gray-400">Fri</div>
        <div className="text-gray-500 dark:text-gray-400">Sat</div>
        <div className="rounded-full bg-gray-100 dark:bg-gray-800 text-gray-900 dark:text-gray-50 p-2">1</div>
        <div className="rounded-full bg-gray-100 dark:bg-gray-800 text-gray-900 dark:text-gray-50 p-2">2</div>
        <div className="rounded-full bg-gray-100 dark:bg-gray-800 text-gray-900 dark:text-gray-50 p-2">3</div>
        <div className="rounded-full bg-gray-100 dark:bg-gray-800 text-gray-900 dark:text-gray-50 p-2">4</div>
        <div className="rounded-full bg-gray-100 dark:bg-gray-800 text-gray-900 dark:text-gray-50 p-2">5</div>
        <div className="rounded-full bg-gray-100 dark:bg-gray-800 text-gray-900 dark:text-gray-50 p-2">6</div>
        <div className="rounded-full bg-gray-100 dark:bg-gray-800 text-gray-900 dark:text-gray-50 p-2">7</div>
        <div className="rounded-full bg-gray-900 text-white p-2 dark:bg-gray-50">8</div>
        <div className="rounded-full bg-gray-100 dark:bg-gray-800 text-gray-900 dark:text-gray-50 p-2">9</div>
        <div className="rounded-full bg-gray-100 dark:bg-gray-800 text-gray-900 dark:text-gray-50 p-2">10</div>
        <div className="rounded-full bg-gray-100 dark:bg-gray-800 text-gray-900 dark:text-gray-50 p-2">11</div>
        <div className="rounded-full bg-gray-100 dark:bg-gray-800 text-gray-900 dark:text-gray-50 p-2">12</div>
        <div className="rounded-full bg-gray-100 dark:bg-gray-800 text-gray-900 dark:text-gray-50 p-2">13</div>
        <div className="rounded-full bg-gray-100 dark:bg-gray-800 text-gray-900 dark:text-gray-50 p-2">14</div>
        <div className="rounded-full bg-gray-100 dark:bg-gray-800 text-gray-900 dark:text-gray-50 p-2">15</div>
        <div className="rounded-full bg-gray-100 dark:bg-gray-800 text-gray-900 dark:text-gray-50 p-2">16</div>
        <div className="rounded-full bg-gray-100 dark:bg-gray-800 text-gray-900 dark:text-gray-50 p-2">17</div>
        <div className="rounded-full bg-gray-100 dark:bg-gray-800 text-gray-900 dark:text-gray-50 p-2">18</div>
        <div className="rounded-full bg-gray-100 dark:bg-gray-800 text-gray-900 dark:text-gray-50 p-2">19</div>
        <div className="rounded-full bg-gray-100 dark:bg-gray-800 text-gray-900 dark:text-gray-50 p-2">20</div>
        <div className="rounded-full bg-gray-100 dark:bg-gray-800 text-gray-900 dark:text-gray-50 p-2">21</div>
        <div className="rounded-full bg-gray-100 dark:bg-gray-800 text-gray-900 dark:text-gray-50 p-2">22</div>
        <div className="rounded-full bg-gray-100 dark:bg-gray-800 text-gray-900 dark:text-gray-50 p-2">23</div>
        <div className="rounded-full bg-gray-100 dark:bg-gray-800 text-gray-900 dark:text-gray-50 p-2">24</div>
        <div className="rounded-full bg-gray-100 dark:bg-gray-800 text-gray-900 dark:text-gray-50 p-2">25</div>
        <div className="rounded-full bg-gray-100 dark:bg-gray-800 text-gray-900 dark:text-gray-50 p-2">26</div>
        <div className="rounded-full bg-gray-100 dark:bg-gray-800 text-gray-900 dark:text-gray-50 p-2">27</div>
        <div className="rounded-full bg-gray-100 dark:bg-gray-800 text-gray-900 dark:text-gray-50 p-2">28</div>
        <div className="rounded-full bg-gray-100 dark:bg-gray-800 text-gray-900 dark:text-gray-50 p-2">29</div>
        <div className="rounded-full bg-gray-100 dark:bg-gray-800 text-gray-900 dark:text-gray-50 p-2">30</div>
        <div className="rounded-full bg-gray-100 dark:bg-gray-800 text-gray-900 dark:text-gray-50 p-2">31</div>
      </div>
    </div>
  )
}

function ChevronLeftIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m15 18-6-6 6-6" />
    </svg>
  )
}


function ChevronRightIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m9 18 6-6-6-6" />
    </svg>
  )
}
